<?php

namespace AppBundle\Repository;

/**
 * Sous_CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sous_CategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
