<?php

namespace AmirBundle\Repository;

/**
 * SouscategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
