<?php

namespace AmirBundle\Repository;

/**
 * ZAARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZAARepository extends \Doctrine\ORM\EntityRepository
{
}
