App_bon_plan_ajout_restaurant:
    path:     /ajout_restaurant
    defaults: { _controller: AmirBundle:Etablissement:ajout_restaurant }
App_bon_plan_ajout_hotel:
    path:     /ajout_hotel
    defaults: { _controller: AmirBundle:Etablissement:ajout_hotel }
App_bon_plan_list_restaurant:
    path:     /list_restaurant
    defaults: { _controller: AmirBundle:Etablissement:list_restaurant }
App_bon_plan_profil_restaurant:
    path:     /profil_restaurant/{id}
    defaults: { _controller: AmirBundle:Etablissement:profil_restaurant }
App_bon_plan_profil_hotel:
    path:     /profil_hotel/{id}
    defaults: { _controller: AmirBundle:Etablissement:profil_hotel }
App_bon_plan_update_restaurant:
    path:     /update_restaurant/{id}
    defaults: { _controller: AmirBundle:Etablissement:update }
App_bon_plan_update_hotel:
    path:     /update_hotel/{id}
    defaults: { _controller: AmirBundle:Etablissement:updatehotel }
App_bon_plan_delete_restaurant:
    path:     /delete_restaurant/{id}
    defaults: { _controller: AmirBundle:Etablissement:delete }
App_bon_plan_list_hotels:
    path:     /list_hotels
    defaults: { _controller: AmirBundle:Etablissement:list_hotels }
App_bon_plan_ajout_etablissement:
    path:     /ajout_etablissement
    defaults: { _controller: AmirBundle:Etablissement:ajout_etablissement }
App_bon_plan_list_beaute_et_bien_etre:
    path:     /list_beaute_et_bien_etre
    defaults: { _controller: AmirBundle:Etablissement:list_beaute_et_bien_etre }