<?php
/**
 * Created by PhpStorm.
 * User: dahem
 * Date: 17/02/2018
 * Time: 00:45
 */

namespace OussamaBundle\Repository;
/**
 * eventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class eventsRepository extends \Doctrine\ORM\EntityRepository
{

}