user_homepage:
    path:     /slema
    defaults: { _controller: UserBundle:Default:index }
solo_ajout:
    path:     /ajouter
    defaults: { _controller: SlimBundle:Categorie:ajoutCategorie }
solo_list:
    path:     /list
    defaults: { _controller: SlimBundle:Categorie:listCategorie }
solo_delete:
    path:     /delete{id}
    defaults: { _controller: SlimBundle:Categorie:deleteCategorie }
solo_ajout2:
    path:     /ajoutS
    defaults: { _controller: SlimBundle:SCategorie:ajoutSCategorie }
solo_list2:
    path:     /listS
    defaults: { _controller: SlimBundle:SCategorie:listSCategorie }
solo_delete2:
    path:     /deleteS{id}
    defaults: { _controller: SlimBundle:SCategorie:deleteSCategorie }
solo_update:
    path:     /update{id}
    defaults: { _controller: SlimBundle:Categorie:update }
solo_update2:
    path:     /Supdate{id}
    defaults: { _controller: SlimBundle:SCategorie:Supdate }
reservation_ajout:
    path:     /ajoutR
    defaults: { _controller: SlimBundle:Reservation:ajoutReservation }
list_reservation:
    path:     /listR
    defaults: { _controller: SlimBundle:Reservation:listReservation }
delete_reservation:
    path:     /deleteR{id}
    defaults: { _controller: SlimBundle:Reservation:deleteReservation }
update_reservation:
    path:     /updateR{id}
    defaults: { _controller: SlimBundle:Rervation:updateReservation }
Mail:
    path:     /mail
    defaults: { _controller: SlimBundle:Mail:Maile }
favoris:
    path:     /favoris{id}
    defaults: { _controller: SlimBundle:Favoris:favoris }



